// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD__qopn55EnZjhsa_k7qjwBdGfpjNQBE8',
    appId: '1:944515994128:web:0c36387bd6445a67027095',
    messagingSenderId: '944515994128',
    projectId: 'chat-app-3423e',
    authDomain: 'chat-app-3423e.firebaseapp.com',
    storageBucket: 'chat-app-3423e.appspot.com',
    measurementId: 'G-88L2JSER8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRgA-lEP46ACCALYcCaE2cxmYhglS7mqo',
    appId: '1:944515994128:android:a77568d81cd5370e027095',
    messagingSenderId: '944515994128',
    projectId: 'chat-app-3423e',
    storageBucket: 'chat-app-3423e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeSuZ1v1ILRzEhYFH9f7ExM-u0dxLUdaY',
    appId: '1:944515994128:ios:974aab564554d147027095',
    messagingSenderId: '944515994128',
    projectId: 'chat-app-3423e',
    storageBucket: 'chat-app-3423e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeSuZ1v1ILRzEhYFH9f7ExM-u0dxLUdaY',
    appId: '1:944515994128:ios:a129b9602fa8e78f027095',
    messagingSenderId: '944515994128',
    projectId: 'chat-app-3423e',
    storageBucket: 'chat-app-3423e.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
